# Generated by Django 5.2.17 on 2026-09-10 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOOKUP', 'Lookup'), ('VLAN_CHANGE', 'VLAN change'), ('LOGIN', 'Login')], max_length=20)),
                ('facility_code', models.CharField(blank=True, max_length=6)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('switch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.switch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
