# Generated by Django 5.2.17 on 2026-09-10 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17, unique=True)),
                ('interface_name', models.CharField(max_length=20)),
                ('vlan_id', models.PositiveSmallIntegerField(help_text='Raw VLAN ID as reported by the switch.')),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_observations', to='inventory.switch')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
