# Generated by Django 5.2.17 on 2026-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portobservation',
            name='last_live_discovery_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
