# Generated by Django 5.2.17 on 2026-09-10 02:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Example: F19114', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Facility code must be F followed by exactly five digits, such as F19114.', regex='^F\\d{5}$')])),
                ('name', models.CharField(help_text='Friendly name shown to helpdesk users.', max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly inventory name, e.g. MDF-STACK-01.', max_length=100)),
                ('hostname', models.CharField(help_text='DNS name, for reference only.', max_length=255, unique=True)),
                ('management_ip', models.GenericIPAddressField(help_text='IP the automation connects to.', unique=True)),
                ('closet_role', models.CharField(choices=[('mdf', 'MDF'), ('idf', 'IDF')], max_length=3)),
                ('model_family', models.CharField(choices=[('ICX7150', 'ICX 7150'), ('ICX7250', 'ICX 7250'), ('ICX8200', 'ICX 8200')], max_length=20)),
                ('stack_member_count', models.PositiveSmallIntegerField(default=1, help_text='Physical units in this logical stack. Does not create separate switch rows.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('fastiron_version', models.CharField(blank=True, help_text='Example: 10.0.10', max_length=80)),
                ('location_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switches', to='inventory.facility')),
                ('upstream_switch', models.ForeignKey(blank=True, help_text='Direct upstream managed logical switch; may be an MDF or another IDF.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downstream_switches', to='inventory.switch')),
            ],
            options={
                'ordering': ['facility__code', 'closet_role', 'name'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'name'), name='unique_switch_name_per_facility')],
            },
        ),
        migrations.CreateModel(
            name='VlanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Helpdesk-facing name, e.g. Guest or Vendor.', max_length=80)),
                ('vlan_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('assignment_mode', models.CharField(choices=[('static', 'Static / manually managed'), ('policy_controlled', 'Policy-controlled (802.1X/RADIUS)')], default='static', max_length=25)),
                ('requester_ad_group', models.CharField(help_text='Exact AD security-group name.', max_length=255)),
                ('allow_helpdesk_port_change', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vlan_profiles', to='inventory.facility')),
            ],
            options={
                'ordering': ['facility__code', 'label'],
                'indexes': [models.Index(fields=['facility', 'is_active'], name='inventory_v_facilit_e399fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('facility', 'label'), name='unique_vlan_profile_label_per_facility')],
            },
        ),
    ]
