# Generated by Django 5.2.17 on 2026-09-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='stack_member_count',
        ),
    ]
