# Generated by Django 5.2.17 on 2026-09-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_switch_stack_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlanprofile',
            name='requester_ad_group',
            field=models.CharField(blank=True, help_text='Optional AD security-group name; not used for current authorization.', max_length=255),
        ),
    ]
