# Generated by Django 5.2.17 on 2026-09-10 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VlanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=17)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('previous_vlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vlanprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requested_vlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vlanprofile')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.switch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
