# Generated by Django 5.2.17 on 2026-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_vlanchangelog_approved_at_vlanchangelog_approved_by_and_more'),
        ('inventory', '0003_alter_vlanprofile_requester_ad_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlanchangelog',
            old_name='previous_vlan',
            new_name='previous_vlan_profile',
        ),
        migrations.AddField(
            model_name='vlanchangelog',
            name='previous_vlan',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _copy_previous_vlan_ids(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='vlanchangelog',
            name='previous_vlan',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RemoveField(
            model_name='vlanchangelog',
            name='previous_vlan_profile',
        ),
    ]


def _copy_previous_vlan_ids(apps):
    Change = apps.get_model('changes', 'VlanChangeLog')
    VlanProfile = apps.get_model('inventory', 'VlanProfile')
    profiles = dict(VlanProfile.objects.values_list('pk', 'vlan_id'))
    for change in Change.objects.all().iterator():
        change.previous_vlan = profiles[change.previous_vlan_profile_id]
        change.save(update_fields=['previous_vlan'])
